In [169]:
from sklearn import datasets
digits = datasets.load_digits()
print(digits.data.shape)
print(digits.target.shape)
print(digits.images[0])
from sklearn.model_selection import train_test_split
x = digits.data
y = digits.target
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=5)
from sklearn import svm
from sklearn import metrics
classifier = svm.SVC()
classifier.fit(x, y)

(1797, 64)
(1797,)
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


SVC()

In [170]:
import numpy as np
import matplotlib.image as mpimg
img = mpimg.imread('number3.png')
def rgb2gray(rgb):
    img_array = np.dot(rgb[...,:3], [0.299,0.587,0.114])
    img_array = (16 - (img_array*16)).astype(int)
    img_array = img_array.flatten()
    return img_array
previsao = classifier.predict([rgb2gray(img)])
print(previsao)

[1]


In [171]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x, y)
previsao_logreg = logreg.predict([rgb2gray(img)])
print(previsao_logreg)

[1]


c:\users\andre\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
